FROM python:3.10-alpine

WORKDIR /app/

COPY ./app/requirements.txt  /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app
ENV PYTHONPATH=/app

COPY ./start-reload.sh /

EXPOSE 80